apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce
  labels:
    app: cloud-config
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
        version: v1    
    spec:
      initContainers:
      - name: wait-for-zipkin
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://zipkin:9411/; do echo waiting for zipkin; sleep 5; done']      
      - name: wait-for-service-discovery
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://service-discovery:8761/actuator/health; do echo waiting for service-discovery; sleep 5; done']      
      containers:
      - name: cloud-config
        image: salazq/cloud-config:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 9296
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"        
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:9411/"
        - name: EUREKA_INSTANCE
          value: "cloud-config"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9296
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce
  labels:
    app: cloud-config
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - protocol: TCP
      port: 9296
      targetPort: 9296
