features:
  newCheckoutProcess:
    enabled: true
  experimentalDashboard:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
