apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce
  labels:
    app: service-discovery
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        version: v1    
    spec:
      initContainers:
      - name: wait-for-zipkin
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://zipkin:9411/; do echo waiting for zipkin; sleep 5; done']        
      containers:
      - name: service-discovery
        image: salazq/service-discovery:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://grafana-k8s-monitoring-alloy-receiver.ecommerce.svc.cluster.local:9411/"
        - name: EUREKA_INSTANCE
          value: "service-discovery"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
