apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: NodePort
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 8761 
