apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:      
      - name: wait-for-cloud-config
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://cloud-config:9296/actuator/health; do echo waiting for cloud-config; sleep 5; done']
      - name: wait-for-service-discovery
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://service-discovery:8761/actuator/health; do echo waiting for service-discovery; sleep 5; done']
      # - name: wait-for-product-service
      #   image: curlimages/curl:7.85.0
      #   command: ['sh', '-c', 'until curl -f http://product-service:8500/product-service/actuator/health; do echo waiting for product-service; sleep 5; done']
      containers:
      - name: user-service
        image: salazq/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8700        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_INSTANCE
          value: "user-service"
        readinessProbe:
          httpGet:
            path: /user-service/actuator/health
            port: 8700
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
