# Pipeline de prueba con fallo sintético y notificación a Logic App
trigger:
 none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Tu Logic App webhook URL
  LOGIC_APP_WEBHOOK: 'https://prod-56.westus.logic.azure.com:443/workflows/e6a26998771d4739b79204f1ddd54491/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AMTXYf0tRkscjsz60bI226Tob4riU3XEfXa1ZLNjeiY'

stages:

# Stage sintético que SIEMPRE falla (para testing)
- stage: SyntheticFailure
  displayName: 'Test Stage (Always Fails)'
  jobs:
  - job: FailingJob
    displayName: 'Synthetic Failing Job'
    steps:
    - script: |
        echo "Running tests..."
        echo "This step will always fail for testing purposes"
        sleep 1
        echo "Simulating test failure..."
        exit 1
      displayName: 'Failing Test Step'
    
    - script: |
        echo "This step will never run because the previous one failed"
      displayName: 'Unreachable Step'

- stage: AlwaysNotify
  displayName: 'Final Notification'
  condition: always()
  dependsOn: SyntheticFailure
  jobs:
  - job: ConditionalNotification
    displayName: 'Send Conditional Notification'
    pool:
      vmImage: 'windows-latest'
    steps:
    - powershell: |
        $stageFailed = "$(Agent.JobStatus)" -eq "Failed" -or "$(Agent.JobStatus)" -eq "PartiallySucceeded"
        
        if ($stageFailed) {
          Write-Host "Sending failure notification..."
          
          $body = @{
            attachments = @(
              @{
                contentType = "application/vnd.microsoft.teams.card.adaptive"
                content = @{
                  type = "AdaptiveCard"
                  version = "1.0"
                  body = @(
                    @{
                      type = "TextBlock"
                      text = "Pipeline Failure Alert"
                      weight = "Bolder"
                      size = "Medium"
                      color = "Attention"
                    },
                    @{
                      type = "TextBlock"
                      text = "Pipeline: $(Build.DefinitionName)"
                    },
                    @{
                      type = "TextBlock"
                      text = "Status: Failed ❌"
                      color = "Attention"
                    },
                    @{
                      type = "TextBlock"
                      text = "Build Number: $(Build.BuildNumber)"
                    },
                    @{
                      type = "TextBlock"
                      text = "Branch: $(Build.SourceBranchName)"
                    }
                  )
                }
              }
            )
          } | ConvertTo-Json -Depth 10
          
          Invoke-WebRequest -Uri "https://prod-56.westus.logic.azure.com:443/workflows/e6a26998771d4739b79204f1ddd54491/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AMTXYf0tRkscjsz60bI226Tob4riU3XEfXa1ZLNjeiY" -Method POST -Headers @{"Content-Type"="application/json"} -Body $body
        } else {
          Write-Host "Pipeline succeeded, no notification needed."
        }
      displayName: 'Conditional Teams Notification'