trigger:
  branches:
    include:
      - stage
  paths:
    include:
      - service-discovery/**
      - cloud-config/**
      - api-gateway/**
      - proxy-client/**
      - order-service/**
      - product-service/**
      - user-service/**
      - shipping-service/**
      - payment-service/**
      - favourite-service/**
      - nginx/**

variables:
  - group: variable-group-taller
  - name: tag
    value: latest
  - name: aksResourceGroup
    value: 'dev-resource-group'
  - name: aksClusterName
    value: 'dev-aks-cluster'
  - name: kubernetesNamespace
    value: 'ecommerce'
  - name: dockerHubUsername
    value: 'salazq'
  - name: base_url
    value: '57.152.56.110'

stages:

- stage: Tests
  displayName: 'Run Tests and Coverage for All Services'
  jobs:
    - job: RunAllTests
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: Maven@4
          displayName: 'Run Tests and Generate Coverage'
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify'
            options: '-Dmaven.test.failure.ignore=false -Dspring.profiles.active=test'
            publishJUnitTestResults: true
            testResultsFiles: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false 
        
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
          
        - task: PublishCodeCoverageResults@2
          inputs:
            summaryFileLocation: 'jacoco-report-aggregation/target/site/jacoco-aggregate/jacoco.xml'
            pathToSources: 'jacoco-report-aggregation/target/site/jacoco-aggregate'

        - task: Docker@2
          displayName: Build and Push cloud-config
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/cloud-config'
            command: 'buildAndPush'
            Dockerfile: 'cloud-config/Dockerfile'
            buildContext: 'cloud-config/'
            tags: '$(tag)'

        # service-discovery
        - task: Docker@2
          displayName: Build and Push service-discovery
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/service-discovery'
            command: 'buildAndPush'
            Dockerfile: 'service-discovery/Dockerfile'
            buildContext: 'service-discovery/'
            tags: '$(tag)'

        # api-gateway
        - task: Docker@2
          displayName: Build and Push api-gateway
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/api-gateway'
            command: 'buildAndPush'
            Dockerfile: 'api-gateway/Dockerfile'
            buildContext: 'api-gateway/'
            tags: '$(tag)'

        # proxy-client
        - task: Docker@2
          displayName: Build and Push proxy-client
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/proxy-client'
            command: 'buildAndPush'
            Dockerfile: 'proxy-client/Dockerfile'
            buildContext: 'proxy-client/'
            tags: '$(tag)'

        # order-service
        - task: Docker@2
          displayName: Build and Push order-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/order-service'
            command: 'buildAndPush'
            Dockerfile: 'order-service/Dockerfile'
            buildContext: 'order-service/'
            tags: '$(tag)'

        # product-service
        - task: Docker@2
          displayName: Build and Push product-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/product-service'
            command: 'buildAndPush'
            Dockerfile: 'product-service/Dockerfile'
            buildContext: 'product-service/'
            tags: '$(tag)'

        # user-service
        - task: Docker@2
          displayName: Build and Push user-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/user-service'
            command: 'buildAndPush'
            Dockerfile: 'user-service/Dockerfile'
            buildContext: 'user-service/'
            tags: '$(tag)'

        # shipping-service
        - task: Docker@2
          displayName: Build and Push shipping-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/shipping-service'
            command: 'buildAndPush'
            Dockerfile: 'shipping-service/Dockerfile'
            buildContext: 'shipping-service/'
            tags: '$(tag)'

        # payment-service
        - task: Docker@2
          displayName: Build and Push payment-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/payment-service'
            command: 'buildAndPush'
            Dockerfile: 'payment-service/Dockerfile'
            buildContext: 'payment-service/'
            tags: '$(tag)'

        # favourite-service
        - task: Docker@2
          displayName: Build and Push favourite-service
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/favourite-service'
            command: 'buildAndPush'
            Dockerfile: 'favourite-service/Dockerfile'
            buildContext: 'favourite-service/'
            tags: '$(tag)'

        # nginx (as reverse proxy or static content)
        - task: Docker@2
          displayName: Build and Push nginx
          inputs:
            containerRegistry: 'docker-hub-service'
            repository: 'salazq/nginx'
            command: 'buildAndPush'
            Dockerfile: 'nginx/Dockerfile'
            buildContext: 'nginx/'
            tags: '$(tag)'

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Tests
  jobs:
  - deployment: DeployToAKS
    displayName: 'Deploy Microservices to AKS'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Get AKS credentials'
            inputs:
              azureSubscription: $(AZURE_ACCOUNT)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing
          - task: Kubernetes@1
            displayName: 'Create Namespace'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/namespace.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: Kubernetes@1
            displayName: 'Deploy Zipkin'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/zipkin.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: Kubernetes@1
            displayName: 'Deploy Cloud Config Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/cloud-config.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Service Discovery'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/service-discovery.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: Kubernetes@1
            displayName: 'Deploy API Gateway'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/api-gateway.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: Kubernetes@1
            displayName: 'Deploy User Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/user-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Product Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/product-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Order Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/order-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Payment Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/payment-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Favourite Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/favourite-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Shipping Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/shipping-service.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Proxy Client'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/proxy-client.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Deploy Nginx'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'apply'
              arguments: '-f k8s-aks/nginx.yaml'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Verify Deployment Status'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'get'
              arguments: 'pods -n $(kubernetesNamespace)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              
          - task: Kubernetes@1
            displayName: 'Get Services Status'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(AZURE_ACCOUNT)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: 'get'
              arguments: 'services -n $(kubernetesNamespace)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

- stage: GetNginxIP
  displayName: 'Obtener IP pública de nginx-proxy'
  dependsOn: Deploy
  jobs:
    - job: CaptureNginxIP
      displayName: 'Capturar IP del servicio nginx'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureCLI@2
          displayName: 'Login to Azure y obtener credenciales del clúster'
          inputs:
            azureSubscription: '$(AZURE_ACCOUNT)'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing

        - script: |
            echo "Esperando IP pública del servicio nginx..."
            for i in {1..10}; do
              IP=$(kubectl get svc $(nginxServiceName) -n $(kubernetesNamespace) -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
              if [[ -n "$IP" ]]; then
                echo "IP pública obtenida: $IP"
                echo "##vso[task.setvariable variable=NGINX_PUBLIC_IP;isOutput=true]$IP"
                break
              else
                echo "IP aún no disponible, reintentando en 10 segundos..."
                sleep 10
              fi
            done
          displayName: 'Capturar IP pública del nginx'
          name: CaptureIP



- stage: TestAPI
  displayName: 'API Testing with Newman'
  jobs:
  - job: RunPostmanTests
    displayName: 'Run Postman Collections'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install newman newman-reporter-htmlextra -g'
      displayName: 'Install Newman and htmlextra reporter'
    - task: NewmanPostman@4
      inputs:
        collectionSourceType: 'file'
        collectionFileSource: 'postman-collections'
        Contents: '**/*.postman_collection.json'
        environmentSourceType: 'none'
        envVars: 'baseUrl=$(base_url)'
        reporters: 'htmlextra'
        htmlExtraDarkTheme: true
        htmlExtraLogs: true
        htmlExtraTestPaging: true
      displayName: 'Run Newman API Tests'


    


- stage: LoadTests
  displayName: 'Run Load Tests with Locust'
  dependsOn: GetNginxIP
  condition: succeeded()
  variables:
    nginxPublicIP: $[ stageDependencies.GetNginxIP.CaptureNginxIP.outputs['CaptureIP.NGINX_PUBLIC_IP'] ]
  jobs:
    - job: Load
      displayName: 'Load Testing with Locust'
      pool:
        vmImage: 'windows-latest'
      steps:
        - checkout: self

        # Instalar Python
        - task: UsePythonVersion@0
          displayName: 'Install Python'
          inputs:
            versionSpec: '3.9'
            addToPath: true

        # Instalar dependencias de Locust
        - task: PowerShell@2
          displayName: 'Install Locust Dependencies'
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "📦 Installing Locust and dependencies..."
              python -m pip install --upgrade pip
              pip install -r load-testing/requirements.txt
              Write-Host "✅ Locust dependencies installed successfully"
              python -m locust --version

        # Ejecutar pruebas de carga
        - task: PowerShell@2
          displayName: 'Run Locust Load Tests'
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "🌐 Using Public IP: $(nginxPublicIP)"
              $env:PUBLIC_IP = "$(nginxPublicIP)"
              powershell -ExecutionPolicy Bypass -File load-testing\run-locust.ps1

        # Publicar resultados
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'load-testing/resultados-carga'
            artifactName: 'locust-load-results'

- stage: NotifyFailure
  displayName: "Notificar Fallo en Teams"
  dependsOn:
    - Tests
    - Deploy
    - GetNginxIP
    - LoadTests
  condition: failed()
  jobs:
    - job: NotifyJob
      steps:
        - task: PowerShell@2
          displayName: 'Enviar mensaje a Teams'
          inputs:
            targetType: 'inline'
            script: |
              Invoke-WebRequest -Uri "https://prod-56.westus.logic.azure.com:443/workflows/e6a26998771d4739b79204f1ddd54491/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AMTXYf0tRkscjsz60bI226Tob4riU3XEfXa1ZLNjeiY" `
                -Method POST `
                -Headers @{ "Content-Type" = "application/json" } `
                -Body '{
                  "attachments": [{
                    "contentType": "application/vnd.microsoft.teams.card.adaptive",
                    "content": {
                      "type": "AdaptiveCard",
                      "version": "1.0",
                      "body": [
                        { "type": "TextBlock", "text": "🚨 *Pipeline Fallida*", "weight": "Bolder", "size": "Medium", "color": "Attention" },
                        { "type": "TextBlock", "text": "🔧 Proyecto: ecommerce-microservice-backend-app" },
                        { "type": "TextBlock", "text": "🧪 Estado: Fallido" },
                        { "type": "TextBlock", "text": "🌿 Rama: $(Build.DefinitionName)" },
                        { "type": "TextBlock", "text": "👤 Ejecutado por: $(Build.RequestedFor)" },
                        {
                          "type": "TextBlock",
                          "text": "[🔍 Ver logs](https://dev.azure.com/salazq/ecommerce-microservice-backend-app/_build/results?buildId=$(Build.BuildId))",
                          "wrap": true
                        }
                      ]
                    }
                  }]
                }'

