trigger: none

variables:
  - group: variable-group-taller
  - name: environmentPath
    value: 'terraform/environments/$(environment)'
  - name: aksResourceGroup
    value: 'dev-resource-group'
  - name: aksClusterName
    value: 'dev-aks-cluster'
  - name: kubernetesNamespace
    value: 'ecommerce'
  - name: nginxServiceName
    value: 'nginx'

stages:

# -----------------------------
# UNIT & INTEGRATION TESTS
# -----------------------------
- stage: Tests
  displayName: 'Run Tests and Coverage for All Services'
  jobs:
    - job: RunAllTests
      pool:
        vmImage: 'windows-latest'
      steps:
        - checkout: self        # Ejecuta todos los tests (unitarios, integración, etc.) y cobertura
        - task: Maven@4
          displayName: 'Run Tests and Generate Coverage'
          inputs:
            mavenPomFile: 'pom.xml'  # pom padre que llama a todos los módulos
            goals: 'clean verify'    # JaCoCo se ejecuta en fase verify
            options: '-Dmaven.test.failure.ignore=false -Dspring.profiles.active=test'
            publishJUnitTestResults: true
            testResultsFiles: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion' 
            jdkVersionOption: '1.11'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false        # Publica solo el reporte agregado de JaCoCo
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish Aggregate Coverage Report'
          condition: succeeded()
          inputs:
            codeCoverageTool: 'JaCoCo'
            summaryFileLocation: 'jacoco-report-aggregation/target/site/jacoco-aggregate/jacoco.xml'
            reportDirectory: 'jacoco-report-aggregation/target/site/jacoco-aggregate'
            failIfCoverageEmpty: false

        # Publica solo el reporte HTML agregado como artefacto descargable
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Aggregate Coverage HTML Report'
          condition: succeeded()
          inputs:
            pathToPublish: 'jacoco-report-aggregation/target/site/jacoco-aggregate'
            artifactName: 'AggregateCoverageReport'
            publishLocation: 'Container'
